version: "3"
services:
  grpc-server:
    build:
      context: ./SmartCitiesGrpc
      dockerfile: Dockerfile
    container_name: smartcitygrpc
    ports:
      - "5216:5216"
    depends_on:
      - mysql-db
    networks:
      - app-network

  nodejs-rest:
    build:
      context: ./RestService
      dockerfile: Dockerfile
    container_name: nodeservice
    ports:
      - "3000:3000"
    depends_on:
      - grpc-server
    networks:
      - app-network

  mysql-db:
    image: mysql:latest
    container_name: mysql-db
    ports:
      - "3306:3306"
    networks:
      - app-network
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: smart_cities

networks:
  app-network:
    driver: bridge
